"use client";

export const list = [
  { id: 31, name: "Product Group Master" },
  { id: 85, name: "Branch Master" },
  { id: 320, name: "Employee Exp Master" },
  { id: 71, name: "Godown Master" },
  { id: 88, name: "Country Master" },
  { id: 3, name: "State Master" },
  { id: 2, name: "District Master" },
  { id: 1, name: "Tehsil Master" },
  { id: 91, name: "Region Master" },
  { id: 11, name: "Department Master" },
  { id: 17, name: "Enquiry Source Master" },
  { id: 18, name: "Payment Mode Master" },
  { id: 19, name: "Cancel Reason Master" },
  { id: 32, name: "Mechanic Master" },
  { id: 404, name: "Cost Center Master" },
  { id: 401, name: "Tyre Pattern Master" },
  { id: 51, name: "Tyre Master" },
  { id: 54, name: "Tyre Category Master" },
  { id: 55, name: "Sub Category Master" },
  { id: 56, name: "Tyre Type Master" },
  { id: 39, name: "Instrument Master" },
  { id: 58, name: "Chapter Type Master" },
  { id: 59, name: "Bank Name Master" },
  { id: 60, name: "Customer Segment Master" },
  { id: 61, name: "Customer Category Master" },
  { id: 73, name: "Tariff class Master" },
  { id: 72, name: "UOM Master" },
  { id: 622, name: "Offer Type Master" },
  { id: 6, name: "Order Type Master" },
  { id: 74, name: "Bill Currency Master" },
  { id: 75, name: "Payment Mode Master" },
  { id: 610, name: "Deduction Master" },
  { id: 619, name: "Group Head Master" },
  { id: 620, name: "Team Leader" },
  { id: 623, name: "PURCHASE PAYOUT" },
  { id: 625, name: "CATEGORY" },
  { id: 626, name: "CLUSTER" },
  { id: 627, name: "CHANNEL" },
  { id: 628, name: "COSTCENTRE" },
  { id: 629, name: "Doc Management" },
  { id: 9, name: "Insurance Company Master" },
  { id: 630, name: "Bank Department Master" },
  { id: 631, name: "Physical Location Master" },
  { id: 633, name: "Employee Assestment And Rating" },
  { id: 634, name: "Apraisal Cycle" },
  { id: 635, name: "bank payment type" },
  { id: 636, name: "bank Subpayment" },
  { id: 637, name: "RTO Type" },
  { id: 638, name: "Insu Type" },
  { id: 639, name: "EW Type" },
  { id: 640, name: "Registration Purpose" },
  { id: 641, name: "Vehicle Type" },
  { id: 642, name: "permit Category" },
  { id: 643, name: "RTO Office List" },
  { id: 644, name: "Permit Type" },
  { id: 645, name: "Vehicle Class" },
  { id: 646, name: "Vehicle Category" },
  { id: 647, name: "Document Mapping" },
  { id: 648, name: "Enquiry Lost/Cancellation Reason" },
  { id: 649, name: "Price Add-On Master" },
  { id: 650, name: "Price Sub Add-On Master" },
  { id: 651, name: "Customer Document" },
  { id: 652, name: "Enquiry Activity" },
  { id: 653, name: "IT ASSETS" },
  { id: 655, name: "In Emp-EXL-Import" },
  { id: 656, name: "EMP Dropdown Configuration Fields" },
  { id: 654, name: "PF PERCENTAGE" },
  { id: 68, name: "Employee Department" },
  { id: 81, name: "Employee Section" },
  { id: 657, name: "Marital Status" },
  { id: 658, name: "Relation" },
  { id: 95, name: "Employee Designation" },
  { id: 660, name: "RTO INSURANCE MASTER" },
  { id: 661, name: "Evaluation Criteria Master" },
  { id: 662, name: "Emp Punch Type Master" },
  { id: 663, name: "Discount Master" },
  { id: 664, name: "Customer Deal Sheet Master" },
  { id: 665, name: "Expense Templates" },
  { id: 666, name: "EMP Notice Period Master" },
  { id: 667, name: "EMP Sepration Mode Master" },
  { id: 668, name: "EMP Exit Interview Done Master" },
  { id: 669, name: "EMP Resigned Status Master" },
  { id: 670, name: "EMP Sepration Categaory Master" },
  { id: 671, name: "Expense Department" },
  { id: 8, name: "EMP Bank/Finance Master" },
  { id: 672, name: "EMP Grade Master" },
  { id: 673, name: "Manual Gatepass Delay Reason Master" },

];
